"""
report_generator.py
Turns a case dict (from scoring.build_case) into a downloadable PDF
forensic report -- the "evidentiary-grade" output analysts and
investigators can attach to a case file.
"""

from fpdf import FPDF


class ForensicReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "Email Threat Forensic Report", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "AI-Powered Email Threat Detection, GeoLocation & Forensic Intelligence Platform", ln=True, align="C")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def section_title(self, text):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(230, 230, 230)
        self.cell(0, 8, text, ln=True, fill=True)
        self.ln(1)

    def kv_row(self, key, value):
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "B", 10)
        self.multi_cell(0, 6, str(key))
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, str(value) if value not in (None, "") else "-")
        self.ln(1)

    def bullet(self, text):
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, f"- {text}")


def generate_pdf_report(case: dict, output_path: str):
    pdf = ForensicReport()
    pdf.add_page()

    # --- Case meta ---
    pdf.section_title("Case Information")
    pdf.kv_row("Case ID:", case["case_id"])
    pdf.kv_row("Generated (UTC):", case["generated_at"])
    pdf.kv_row("Verdict:", case["verdict"])
    pdf.kv_row("Fraud Score:", f"{case['fraud_score']} / 100")
    pdf.ln(3)

    # --- Email summary ---
    es = case["email_summary"]
    pdf.section_title("Email Summary")
    pdf.kv_row("Subject:", es["subject"])
    pdf.kv_row("From:", es["from"])
    pdf.kv_row("To:", es["to"])
    pdf.kv_row("Reply-To:", es["reply_to"])
    pdf.kv_row("Date:", es["date"])
    pdf.kv_row("URLs found:", ", ".join(es["urls_found"]) if es["urls_found"] else "None")
    pdf.kv_row("Attachments:", ", ".join(es["attachments"]) if es["attachments"] else "None")
    pdf.ln(3)

    # --- Content analysis ---
    ca = case["content_analysis"]
    pdf.section_title("Content / NLP-ML Analysis")
    pdf.kv_row("ML phishing probability:", ca["ml_phishing_probability"])
    pdf.kv_row("Rule-based trigger phrases:", ", ".join(ca["rule_hits"]) if ca["rule_hits"] else "None")
    pdf.kv_row("Combined content score:", ca["combined_score"])
    pdf.kv_row("Content label:", ca["label"])
    pdf.ln(3)

    # --- Header forensics ---
    hf = case["header_forensics"]
    pdf.section_title("Header / Protocol Forensics")
    pdf.kv_row("Sender domain:", hf.get("domain"))
    pdf.kv_row("SPF result:", hf.get("spf"))
    pdf.kv_row("DKIM result:", hf.get("dkim"))
    pdf.kv_row("DMARC result:", hf.get("dmarc"))
    pdf.kv_row("Reply-To mismatch:", hf.get("reply_to_mismatch"))
    pdf.ln(3)

    # --- Origin trace ---
    ot = case["origin_trace"]
    pdf.section_title("Origin Trace / GeoLocation")
    pdf.kv_row("Origin IP:", ot.get("origin_ip"))
    geo = ot.get("geolocation") or {}
    if geo.get("error"):
        pdf.kv_row("Geolocation:", f"Unavailable ({geo['error']})")
    else:
        pdf.kv_row("Country:", geo.get("country"))
        pdf.kv_row("Region / City:", f"{geo.get('region')} / {geo.get('city')}")
        pdf.kv_row("ISP / Org:", f"{geo.get('isp')} / {geo.get('org')}")
        pdf.kv_row("Likely hosting/VPN:", geo.get("likely_hosting_or_vpn"))
    pdf.kv_row("Attribution confidence:", ot.get("attribution_confidence"))

    whois = ot.get("whois") or {}
    if whois and not whois.get("error"):
        pdf.kv_row("WHOIS registrar:", whois.get("registrar"))
        pdf.kv_row("Domain created:", whois.get("creation_date"))
    pdf.ln(3)

    # --- Reasons ---
    pdf.section_title("Reasons for Verdict")
    for r in case["reasons"]:
        pdf.bullet(r)
    pdf.ln(3)

    # --- Disclaimer ---
    pdf.section_title("Forensic Disclaimer")
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "I", 9)
    pdf.multi_cell(
        0, 5,
        "This report is generated by an automated system and represents a "
        "confidence-scored assessment, not definitive proof. Geolocation "
        "accuracy is reduced when the origin IP belongs to a VPN, proxy, "
        "TOR exit node, or cloud hosting provider. This report should be "
        "reviewed by a human analyst before being used in any investigative "
        "or legal proceeding."
    )

    pdf.output(output_path)
    return output_path
